# -*- coding:utf-8 -*-
CONTOUR_AREA_THRESHOLD = 500

COLOR_WHITE = (255, 255, 255)
COLOR_BLUE = (255, 0, 0)
COLOR_GREEN = (0, 255, 0)
COLOR_RED = (0, 0, 255)
COLOR_BLACK = (0, 0, 0)

BLACK_BORDER_THICKNESS = 5
CONTOUR_THICKNESS = 1

POOL_AREA_THRESHOLD = 30000
# SUB_PROC_AREA_THRESHOLD =

POOL_HEADER_H_W_RATIO_CEILING = 100
POOL_HEADER_H_W_RATIO_FLOOR = 4
DEFAULT_POOL_HEADER_WIDTH = 30

BOUNDARY_OFFSET = 3
RECT_DILATION_VALUE = 5
LANES_RECT_DILATION_VALUE = 5

ERODE_KERNEL_SIZE = 2

SEQ_FLOW_THRESHOLD = 20
SEQ_MIN_LENGTH = 10
SEQ_MAX_GAP = 3

LINE_AREA_THRESHOLD = 10
